server:
  port: 8080
  servlet:
    context-path: /api/track-tidy
  error:
    include-exception: true
    include-message: always
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: track-tidy


token:
  signing:
    key: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9